package by.bivis.schedule_bot_model;

public enum UserState {
    NONE,
    START,
    NEWS,
    PICK_SOURCE_CATEGORY,
    PICK_SOURCE_CATEGORY_TO_SEE_WITHOUT_SUBSCRIPTION,
    SOURCES_SUBCATEGORIES,
    SOURCES_SUBCATEGORIES_TO_SEE_WITHOUT_SUBSCRIPTION,
    SOURCES,
    SEE_SCHEDULE_WITHOUT_SUBSCRIPTION,
    PICK_SIGNED_SOURCE,
    PICK_SIGNED_SOURCE_EXTENDED,
    PICK_SIGNED_SOURCE_TO_REMOVE,
    SCHEDULE,
}
